# Project identification
sonar.projectKey=itpzzi_fc-git
sonar.organization=itpzzi
sonar.projectName=Full Cycle Git Study Project
sonar.projectVersion=1.0

# Source config
sonar.sources=src
sonar.language=ts
sonar.sourceEncoding=UTF-8

# Test coverage (ajuste se usar cobertura)
sonar.tests=tests
sonar.test.inclusions=**/*.test.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# TypeScript support
sonar.typescript.tsconfigPath=tsconfig.json